'use client';

import { FormEvent, useEffect, useState } from 'react';
type StoredFlow = { state: string; shop: string; clientId: string; scopes: string; createdAt: number };
type TokenResult = { accessToken: string; scope: string };

export default function ShopifyCallbackPage() {
  const [flow, setFlow] = useState<StoredFlow | null>(null); const [callbackUrl, setCallbackUrl] = useState(''); const [problem, setProblem] = useState(''); const [loading, setLoading] = useState(false); const [result, setResult] = useState<TokenResult | null>(null); const [copied, setCopied] = useState(false); const [tokenCleared, setTokenCleared] = useState(false);
  useEffect(() => {
    let cancelled = false;
    queueMicrotask(() => {
      if (cancelled) return;
      const current = new URL(window.location.href); const raw = sessionStorage.getItem('dsa-shopify-oauth');
      if (!raw) { setProblem('Deze terugkeerpagina hoort niet bij een actieve koppeling. Start opnieuw via de generator.'); return; }
      try { const stored = JSON.parse(raw) as StoredFlow; if (current.searchParams.get('state') !== stored.state) { setProblem('De beveiligingscontrole is mislukt. Start opnieuw via de generator.'); return; } if (Date.now() - stored.createdAt > 15 * 60 * 1000) { setProblem('Deze koppeling is verlopen. Start opnieuw; de autorisatie moet binnen 15 minuten worden afgerond.'); return; } if (current.searchParams.get('shop') !== stored.shop || !current.searchParams.get('code') || !current.searchParams.get('hmac')) { setProblem('Shopify stuurde geen complete autorisatie terug. Start opnieuw via de generator.'); return; } setFlow(stored); setCallbackUrl(current.toString()); } catch { setProblem('De lokale beveiligingscontrole kon niet worden gelezen. Start opnieuw via de generator.'); }
    });
    return () => { cancelled = true; };
  }, []);
  async function exchange(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!flow) return; const form = event.currentTarget; const secretInput = form.elements.namedItem('clientSecret') as HTMLInputElement; const clientSecret = secretInput.value.trim(); if (!clientSecret) return; setLoading(true); setProblem('');
    secretInput.value = '';
    try { const response = await fetch('/shopify-api/api/shopify/oauth/exchange', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ callbackUrl, shop: flow.shop, clientId: flow.clientId, clientSecret }) }); const body = await response.json() as { accessToken?: string; scope?: string; error?: string }; if (!response.ok || !body.accessToken) throw new Error(body.error || 'Shopify gaf geen access token terug.'); setResult({ accessToken: body.accessToken, scope: body.scope || flow.scopes }); sessionStorage.removeItem('dsa-shopify-oauth'); } catch (error) { setProblem(error instanceof Error ? error.message : 'De uitwisseling is mislukt.'); } finally { setLoading(false); }
  }
  async function copyToken() { if (!result || tokenCleared) return; await navigator.clipboard.writeText(result.accessToken); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  return <main className="callback-page"><header className="site-header"><a href="/shopify-api" className="brand"><span>DSA</span> Agents & Skills</a><span className="status"><i /> Beveiligde terugkeer</span></header><section className="callback-shell" aria-live="polite"><p className="eyebrow">LAATSTE STAP</p><h1>{problem ? 'De koppeling is niet afgerond.' : result ? 'Je token is klaar.' : 'Shopify is goedgekeurd.'}</h1>{problem && <div className="callback-error"><strong>Dit ging niet goed</strong><p>{problem}</p><a href="/shopify-api">Opnieuw beginnen</a></div>}{!problem && flow && !result && <form className="secret-form" onSubmit={exchange}><div className="store-confirm"><span>GEKOPPELDE STORE</span><strong>{flow.shop}</strong></div><label><span>Client secret</span><input type="password" name="clientSecret" autoComplete="off" required placeholder="Dev Dashboard → Instellingen → Credentials" /></label><p>Je vindt hem onder <strong>Dev Dashboard → Instellingen → Credentials</strong>. Hij wordt via HTTPS alleen gebruikt om de tijdelijke Shopify-code server-side om te wisselen, niet opgeslagen en vóór de netwerkuitwisseling uit dit veld gewist.</p><button type="submit" disabled={loading}>{loading ? 'Shopify-token ophalen…' : 'Maak mijn permanente token'} <span>→</span></button></form>}{result && <div className="token-result"><span>PERMANENTE OFFLINE ACCESS TOKEN</span>{tokenCleared ? <p><strong>Token gewist van dit scherm.</strong> Je kunt deze code niet opnieuw bekijken. Start opnieuw als je hem niet veilig hebt opgeslagen.</p> : <><div><code>{result.accessToken}</code><button type="button" onClick={copyToken}>{copied ? 'Gekopieerd ✓' : 'Kopieer token'}</button></div><p><strong>Kopieer hem nu.</strong> Sla hem op in de beveiligde secret-invoer van je AI-project als <code>SHOPIFY_ACCESS_TOKEN</code>. Deel hem nergens anders. Deze token blijft geldig totdat de app wordt verwijderd of de toegang wordt ingetrokken.</p><button className="clear-token" type="button" onClick={() => setTokenCleared(true)}>Wis token van dit scherm</button></>}<dl><div><dt>Store</dt><dd>{flow?.shop}</dd></div><div><dt>Scopes</dt><dd>{result.scope}</dd></div></dl></div>}{!problem && !flow && <div className="callback-loading">Beveiligingscontrole uitvoeren…</div>}</section></main>;
}
